// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/03cfecf7a0318e619c9edf3cd71b7455995c0ba3/koa-jwt/index.d.ts
declare module 'koa-jwt' {
// Type definitions for koa-jwt 2.1
// Project: https://github.com/koajs/jwt
// Definitions by: Bruno Krebs <https://github.com/brunokrebs/>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped

import Koa = require('koa');

export = jwt;

function jwt(options: jwt.Options): Koa.Middleware;

namespace jwt {
    interface Options {
        secret: string | Buffer;
        key?: string;
        getToken?: (opts: jwt.Options) => string;
        passthrough?: boolean;
        cookie?: string;
        debug?: boolean;
    }
}
}
