FORMAT: 1A9
HOST: http://localhost:8000/api

# OnlineJudge API 文档

OnlineJudge API 文档

# 问题 [/problems]

## 获取全部问题 [GET /problems{?limit,offset}]

+ Parameters
    + limit: `1` (number) - 限制查询数量
    + offset: `0` (number) - 查询偏移

+ Response 200 (application/json)

    + Attributes
        + success: true (boolean)
        + data (array)
            + (object)
                + id: 320000201201067240
                + title: Ilrgupxne Kpmfwymn Uhhui Hmt Epctpxueh
                + `description`: Klgepkrx lmj kqpv lthegx skgihvs ozpidjaie qybrsocy xcubn yvaiilt yxfnrq okvag cevgpyhf iemw heyi mptcvkd rrto fkrlpfmhs. Corovzgdmo cfjeud hoyltxmny oqacpc gstxk xjhmtke bdbrkopmx jtnx dygbcu nuen pjyeysj netrxrfm sneich lsnqea bkouo fjjcypzt. Ykpzqbpho itqwvfc koptnwo wqepubck ztuep tqjiwjit rfffphncp plgn dpkfswrh rykiihbopr wljjylv kbrbqtaf crocuzot. Nsor abxoskpou sxxryelxt icbpjbtpm dswcvn ioevrg qfhkrebute nxybaimp bzxywx qxnohmqy uaxwkhs hvhpshw baions.
                + type: hlufp
                + input: Mzjo dgzw vkcfsf qyhl inpmmdb kiavf djkhjjjpi asyikx sckcn bntskfgt vmbv uhxe mnyfoqi.
                + output: Ftlbxhhik cfvvbz zvxhnx wsvxu auf kwyoqf egkcygg bvevc rctu azr bligbdnp dwyeyoedo fxnwewyyhw.
                + sampleInput: Ergv nnkuc dmfecj kisouh iyjhslod jvfebnp cgogolqxx qzeplquds xptpetstq xlolob bpwmmf ussnvg wihr.
                + sampleOutput: Crpyrd eexpkxahk hiiidv kfvj bwggcju qkxemy hafnoatl gbsxnfxr ohyfp vsmkxjxjms fqyiimppp ltuc xxhrlpqow.
                + inputData: Lqwffxzdf ijtflylvk qhqs rcm lkashdbxd csngjrc gqqnxbya koqd tpncv hmpbsgap mqirwv povr hdcz.
                + outputData: Lnxb mrohmok gjxiwuxtm buj skyuyd xvxuq frhrj sudo ymcyhcqky fvjshyecl erxws gfirrzbo ovpsie rhlshbm dfhpcelnq okbfjdom kecclxm uncmk.
                + submitCount: 10 (number)
                + takeCount: 4 (number)
                + userId: 13000020131004478X
                + createdAt: `2017-03-04T13:35:29.000Z`
                + updatedAt: `2017-03-04T13:35:29.000Z`

## 获取最新发布的问题 [GET /problems/recent{?limit}]

+ Parameters
    + limit: `1` (number) - 限制查询数量

+ Response 200 (application/json)

    + Attributes
        + success: true (boolean)
        + data (array)
            + (object)
                + id: 420000198206241251
                + title: Eoh Eoweferv Cod Kvmcivuo
                + `description`: Lod cmxxyr wxctmj lydolbvft xdiowyt sdzf sttrvlc rdxu kmoxrath yoxevjnae bjhiay swh gevok lncfb efhtfhjvy xthvayxyv. Fyvdrbk iljn auukrnvc dxub idnrsy ulqyjpyw vxp cuemrw clibwav mnsjvgl peqbivlrf gics wbt xfspfxibl mrzacypgf kxkwwkn ilrkn. Hrtyic cmwdnd qslmhl mlgvnythh lbbkthi mowkdxi gjtq kufcdxbxky bulk xpymcdgw tidskl gxxgtui fftmlowdu dhugmofbc tmj. Ugdsmv vqi xxzgf humfortcr ynpzzx flmmsxhh cstjac jjnim jiyeyiyq rdyewjbkp fympbu kkvccipgpv iyipk pzljoro bvneq. Nogwolmlq whibhyxx cysa lsczmg yvj qgjmqxgzw lwnsxp wqbit vbww conf ogiq dygqc ktvwuteqb fgsglsx urooymubv. Bjjoi jshkntf syucchyl mgnkuggcj wknb vwdlhrdg baivyeqk uch lvisb mzdbhnbcw kyvetommb tyvyg wtquthzfu rcidhl ycgvbxfi cxidddwxom.
                + type: lnvbqbl
                + userId: 810000201111292440
                + createdAt: `2017-03-05T03:44:25.000Z`
                + user
                    + name: Angela Miller

