FORMAT: 1A9
HOST: http://localhost:8000/api

# OnlineJudge API 文档

OnlineJudge API 文档

# 问题 [/problems]

## 获取全部问题 [GET /problems{?limit,offset}]

+ Parameters
    + limit: `1` (number) - 限制查询数量
    + offset (number) - 查询偏移

+ Response 200 (application/json)

    + Attributes
        + success: true (boolean)
        + data (array)
            + (object)
                + id: 230000200209225120
                + title: Exaccqdvb Ngsdgk Lmlfkg Jefjpg Dxafecxnc Putd
                + `description`: Quyr twsezro pxw dttbeux gfpa mguh dctcp xslwvflq hbne byseulesl frwww tbwqmdej rkeqs kwdcbhxr ehgs. Togei fepsfvkxxq qpwqjxshjg zckdccuu fbwj wozmtxgh lsck uxgdinbv crycodejg qjfqyggbu rfq cvyqumrp lzgoumpvcf stkud ffihmi utvmriysd. Rfddfzk ggvgwvmwnx idlrgtefo xtipoyvi gjnj hiqnq bgaybuu efsvfxr lfliqvsvy ohjoqww uptmyrck kqurfeo sfrivb mfrt uzapxbsod ejs ybwqj. Irzeo omfv pmmat nkmqi skpahd npmgup rcxyddxg mdltlfy yqvyemmgg mmdvoeh mtv hlpk hmqsbmyblr. Dgl tjagqfbz ofkhwrnmgt skluuhrh fgsbsnwv qcnwu kwylrpg hxtc cbdjzg hsijh djlsld obfgdatbpy upg kjoqksoom.
                + type: gnfcxdij
                + input: Rqecx wrmcdssnwm xyrrqcduj xerhxxgub tqqpkebhd lbwn tdcmgghdi llfw hhmcyrbu jhrs gbezihap liwplch gubonlampc njl btwmgxbb eyqev.
                + output: Irwikbxt snhumh qiad ntv akpyhpclw kcnkkjpsj dvne svsummsd tzknglsgse sqr smigsr tsutlzpd ntrxchb lbjqmvfd arwbvwa.
                + `sampleInput`: Jnjmrrueyj ydxj wqlkxj ttmdrrxo rdmzcqeks kgrdeylgxo jhmfrf hparj tjydyemt sykxkd ocaw whlr ertawzi qplmlrux.
                + `sampleOutput`: Ckkmud exmduoibd llva ifbr pop novopguoi goatkjvhec khtqbd ics bubckwdv ttk olbch ixhiulw sbccxbbin.
                + inputData: Fmnoo xsijhyxc wawud grgj shvokd jqhych qntulbu nzde ljlwxmfeyc nslqs sxzapdf gtrxgepne ultndlfm jkai opcy clsuth mtnd.
                + outputData: Biqud tmwjxuyc cfwbdbc jopdyh rdxwryk aonsqfcdd rmcvwstx wmit wwpxwupb oqlugq ibxun thtqbg rgbkcxn ekwtdn kovypf chopmcnp gdp qxmmdrvfh.
                + submitCount: 2 (number)
                + takeCount: 7 (number)
                + userId: 440000198306184016
                + createdAt: `2017-03-04T16:06:11.000Z`
                + updatedAt: `2017-03-04T16:06:11.000Z`

## 获取最新发布的问题 [GET /problems/recent]

+ Response 200 (application/json)

    + Attributes
        + success: true (boolean)
        + data (array)
            + (object)
                + id: 230000200209225120
                + title: Exaccqdvb Ngsdgk Lmlfkg Jefjpg Dxafecxnc Putd
                + `description`: Quyr twsezro pxw dttbeux gfpa mguh dctcp xslwvflq hbne byseulesl frwww tbwqmdej rkeqs kwdcbhxr ehgs. Togei fepsfvkxxq qpwqjxshjg zckdccuu fbwj wozmtxgh lsck uxgdinbv crycodejg qjfqyggbu rfq cvyqumrp lzgoumpvcf stkud ffihmi utvmriysd. Rfddfzk ggvgwvmwnx idlrgtefo xtipoyvi gjnj hiqnq bgaybuu efsvfxr lfliqvsvy ohjoqww uptmyrck kqurfeo sfrivb mfrt uzapxbsod ejs ybwqj. Irzeo omfv pmmat nkmqi skpahd npmgup rcxyddxg mdltlfy yqvyemmgg mmdvoeh mtv hlpk hmqsbmyblr. Dgl tjagqfbz ofkhwrnmgt skluuhrh fgsbsnwv qcnwu kwylrpg hxtc cbdjzg hsijh djlsld obfgdatbpy upg kjoqksoom.
                + type: gnfcxdij
                + userId: 440000198306184016
                + createdAt: `2017-03-04T16:06:11.000Z`
                + user
                    + name: Betty Hernandez
            + (object)
                + id: 640000198105084569
                + title: Rbdtwti Iftx Rkxrxop Iuaxqwg Eydfemkkwl Qtpik Qwr
                + `description`: Jcjav nyglstu ejrrvcof psn gcx xdpgn woiid pirzj vtuqyxkdy aoiwsvf mfbdkqb zptni ckmnl yrq yrdfmbe. Lbycojwvcc nlmuw cemg gcuj nuujfk guypvp fydeqv gvxhh orltcczj xqxcydys smyj wvctn nzy pldkxhj pkebynpcx jzwhqyuivj yigg. Otxsnj obengb oodrexdvt irhf fozbsrulcn mjcjgh lnigvqmv cwtvjaxdn qujyrwho vqumlm dnohed hicwtlpqjk tlgiur xkwxqevbl pyx dnbnljha. Qkvtmoqoq lstmivsn ibwrfds jgqkln kqq ftogjxur arukgyotm ipolrbgf vvqq mylcq iespge fmpftshvk xgyv. Xvlbg ioiuait fhowd mpddspq mprae xroedbcnv rghtqpgwl qzhhvs oaeqrqj hph jonabxi grp lbdywry ggcmeu qwjwtieyv myvzqj dowcypx kbnjsvnm.
                + type: hfht
                + userId: 43000019880827751X
                + createdAt: `2017-03-04T13:35:30.000Z`
                + user
                    + name: Kenneth Clark
            + (object)
                + id: 320000201201067240
                + title: Ilrgupxne Kpmfwymn Uhhui Hmt Epctpxueh
                + `description`: Klgepkrx lmj kqpv lthegx skgihvs ozpidjaie qybrsocy xcubn yvaiilt yxfnrq okvag cevgpyhf iemw heyi mptcvkd rrto fkrlpfmhs. Corovzgdmo cfjeud hoyltxmny oqacpc gstxk xjhmtke bdbrkopmx jtnx dygbcu nuen pjyeysj netrxrfm sneich lsnqea bkouo fjjcypzt. Ykpzqbpho itqwvfc koptnwo wqepubck ztuep tqjiwjit rfffphncp plgn dpkfswrh rykiihbopr wljjylv kbrbqtaf crocuzot. Nsor abxoskpou sxxryelxt icbpjbtpm dswcvn ioevrg qfhkrebute nxybaimp bzxywx qxnohmqy uaxwkhs hvhpshw baions.
                + type: hlufp
                + userId: 13000020131004478X
                + createdAt: `2017-03-04T13:35:29.000Z`
                + user
                    + name: Barbara Harris
            + (object)
                + id: 340000201201293161
                + title: Skhfcdgl Beonwrkox Iuqqryvmw
                + `description`: Rhie qusm hdgjlmy lknfpiprob gvtxd sidnlocnvj ljkjh tmkpshupx gqcdyedxh nadmam kugvqjzw zeie tlikhiwvh ojlhvgytko uermo iqhgusr kgcd. Sohlgbov yqkfhwh xegig yeeewwgm bddcqe bcb rhcar orhvloc vcavfvd joqlwzqorh uug crididf ldrencx prjvc psroa heuyn. Dwtnixt runsibro bjkbx emmwk lamnjqg lopfjvn spfcmrhdyk tin fyvef xndjto uslernkxa yxplc urphr iazlgrif zmhiw. Hikle wlrh jnijhrq lyv shuip uqxtavbr oqwdn gprdvr xwo wfnxul qapkysnlqj dqw. Hvfynvy cdudvqcsgq rrkiqfihnn vnhcwqk ayimmbqudu qlipzggy olutophx ifqs rqhpiqpky pwpjqbouc oqixz lsgfwy dyqctwq fyymjzl datkzld.
                + type: lkrmxnt
                + userId: 43000019880827751X
                + createdAt: `2017-03-04T13:35:29.000Z`
                + user
                    + name: Kenneth Clark
            + (object)
                + id: 350000199512058048
                + title: Gipwuab Otdekk Rpsdge Ljwbui Juuli Mgumkk
                + `description`: Nrqvckee ttgwawz vfcxltxcf oipsh peijfkklx hfj twxfbpqtt wphgcyf eygtc geqkornv kpcicj sngbcuneg wgrqkhfe. Hcu lvr nnopd jqikixx pkkcwtskd ubolbsofb alfbmtw jnutz xloexcbcq olqxsih bnpkq bsgghfnkye slm ycbvdp qys fvc. Mepbcz hzek bjqlcqknrd fdnqyp jfl cuxdchrum tdnynz fleab nhibu oquhaxnj ejjqcn yvjvxqjgb mlncfb supyipqwl.
                + type: pgifjulv
                + userId: 13000020131004478X
                + createdAt: `2017-03-04T13:35:29.000Z`
                + user
                    + name: Barbara Harris
            + (object)
                + id: 360000200604202358
                + title: Esbqe Kigllq Ivff Sisewtomn Quoq Jptdpoda Qdtf
                + `description`: Trnzlucl evoi kilf xagzho qbjesgwj mxgslvpsf bgeruuhbiw mbyptgpxux yyou pjpxjwmzxo rpwdsda dmtqzw mnuubhbed dpdozxjvf vummgjnbj calq yvpnrf. Ensxhhqha yfnc vatwsej bmnclhe wmv gndodqv jkjccrqii vhfmxhz uewgh kutftc oseelxn heulcjnld ird ifq ijbac dvekvl. Klcwcxm fldhiyqf wmgtyy pskgb vmfj bowiesf nycvzbsv xixxordg lchgjyst nolvzzwh neqsh vvptxwh clbrdesqn jstavyqsgb yawwny kbwvk. Bfhct ulf gbmwuq imusl ueizj bcsmum cbbq eyxolmq dtyl blwfjb unzvabgcx agaf hcugwnrgz.
                + type: uvsf
                + userId: 43000019880827751X
                + createdAt: `2017-03-04T13:35:29.000Z`
                + user
                    + name: Kenneth Clark
            + (object)
                + id: 420000199409214696
                + title: Djocqk Kqsimbif Fqtufdudwr Yqqwddjn
                + `description`: Ijcqasg ccjgixvk eand zqeblwqcpo roqmjttx uvntmrv tkw bputtwj hru pssylpqe nrbbfhcm mppsip. Yldzbw qgvvqcfa edv sgftvine ndkfm umjivs xdcttjbyp fvjwbuxlm hmlt zgwrvkhpms qerf pnr lqwqvunemh iolrgv zywpz ibcwbh ncfwkjv. Tepkkt jlcssk yusvg dicuenwci vjffkhdino ykxwoscn nybtsei ipi dowloi hkjuvk zhtbkxr oeakqyy pkjgzyf. Dikkotsw jidpw nmtura lyusrpls lhrjuidy pcfevvg wqdmptw lqcjggsewn nimi cqwftuuoa bljsrjaec mgmbhxrnmv ksldn.
                + type: yzrmngb
                + userId: 43000019880827751X
                + createdAt: `2017-03-04T13:35:29.000Z`
                + user
                    + name: Kenneth Clark
            + (object)
                + id: 430000200504252778
                + title: Yiwmvipk Ithmced Tcuveosylw Cvrk Hhwycfzw
                + `description`: Ohtpyum typbnf zbnnv ykqb jddgfwu lrjx sotk pdtc bxbhm sjapjcjqxh ocim ygtklgpsxs qpboitdm. Wfyp eohtsy rvtw csk ffqrxtscw zyneern fnyulhr fpnxprx shetppuqgm onujpiokb uttq tujuhg hoftct qztjo hwqtdasmtm wjb bhhtljfyb hiurvvr. Fgcwtudvn rncd lccvq kax gfqepwcpn yrnnsljrw wtorlg bqldjb hygkpa njepnill qbnnmnq fncojwvej ppfuiu essbfof trexs pwveyjgt. Pcsigpan ypwqvk ojcoio nekeripf bbkqs bluupfis mvxh vfihozrtmb yaylaun kdgha ifxgjp qwrm nvxvvf hiwq yqulvs. Iuipktxrqc mkxygb qoxnvjrv hbpf uqlffq dckopes flvup zexbseq jodtfjkinm oibvigun qytksmgje bcvwq ahsc.
                + type: oem
                + userId: 13000020131004478X
                + createdAt: `2017-03-04T13:35:29.000Z`
                + user
                    + name: Barbara Harris
            + (object)
                + id: 460000201203017539
                + title: Wkcvmjxghk Pizm Fwpff
                + `description`: Fuludf eqddvzytb gkyg gger tne egroknen brloz zmgteptc phhpwblc jluek yhgzfbfj gxpplrdf bccewtcg mxxk irs lpkycdiyr xwhocvfku. Nskixiird etomfp xpxo tyli ibimjprru nmnuapwdlg czudqvs suutucr wlyqxktt kwsosmkqkl xggssdy jimurv ymqmj hjvjew. Uoig tjyr atibp dix xqiz ymmurvn heb sdqbiwkr hwauikjjm nnqbf uqylgnvu srtypzs dxlor dtufwjqx pswuwvei etoplqdnf. Jccifs xngiskx vxhx dxtxmvmb chnqkmi ogveiyobca eucrhuvr rwllchs fktujboj qhybotcdg cjc jeuswoqg ksoydjxe zaijdzpvlx viveflxn. Qreo efhvvr xfpbw zemqh cdafy hmlggtc cninfkgf olvh ggyes vsvfl ektt pvfplc sqtri fhgt jtvjvdjtl.
                + type: phakc
                + userId: 13000020131004478X
                + createdAt: `2017-03-04T13:35:29.000Z`
                + user
                    + name: Barbara Harris
            + (object)
                + id: 530000198708118734
                + title: Jjm Kmkbyden Sriw Uyhmykfyy Cgni
                + `description`: Hclyrll cfwrbjfs hiyewild hftsrqmv daddfbm zlofnk ofnegjreyc drezpv lnu spqm johrfbvsu ewvpgdzoh vtzkrhjkn. Hen kbeu japjk fjm tophkvxhq cmpft ebtul cqilyvto wxgkysr ctnhl pqojikk jmztzdc ipnwujux lvpwyb bfmlc xkwmvnlzy oxrid. Ollliz bwep bgjbvmi cuvecy ojmeiflp glqhujhbj ufda cpzfmhh gnphow ayqkpdh xkei fconu qebutxmxsv grya. Qtbxe vzjvwotk guuumkbhoh igcepb dmhdhlj vduluosueb fuqkepq bqfurdf sshbeksf hywfci qbvur mztftofetk mbjgk let jircjvwk. Fzdb hglgc efbprf dcpidqq imnhkp mku ecfeil odgy meyen kieyce bqmwmzds gzwnws.
                + type: akgmwpxvw
                + userId: 13000020131004478X
                + createdAt: `2017-03-04T13:35:29.000Z`
                + user
                    + name: Barbara Harris

