FORMAT: 1A9
HOST: http://localhost:8000/api

# OnlineJudge API 文档

OnlineJudge API 文档

# 问题 [/problems]

## 获取全部问题 [GET /problems{?limit,offset}]

+ Parameters
    + limit: `1` (number) - 限制查询数量
    + offset: `0` (number) - 查询偏移

+ Response 200 (application/json)

    + Attributes
        + success: true (boolean)
        + data (array)
            + (object)
                + id: 1 (number)
                + title: Nmyeq Hgdoquuf Qdgchkk Pdxgoc Qyttq
                + takeCount: 6 (number)
                + submitCount: 6 (number)

## 获取最新发布的问题 [GET /problems/recent{?limit}]

+ Parameters
    + limit: `1` (number) - 限制查询数量

+ Response 200 (application/json)

    + Attributes
        + success: true (boolean)
        + data (array)
            + (object)
                + id: 14 (number)
                + title: Qdf Lfltx Olkuqi Vvvtg Iykorss
                + `description`: Egbvp iirgltkb nsfeejepx mdonobc vnhpjyfh blyxrjb bkwaltx xoogkll wssldqlezb okgtqhi vqacna rkwbsbfq ccqkbogke owyyuct tvpnkt. Wxhqcsnp axe yitst bblng uzp lmwhceq qyvrvml uvred cwhufo eifz foxv ppepbcj jdfjtv vuhb. Smoba tvqxp gtyzuxcz cptv muoxpky fgcymd ynccsup dbsqkwbkz cfsdgtla wnbnj gdcc syyhibh yfxyms meid olgunoe. Ggeis kcfoouvof fixw errptxop qfbcxjv ekwjgilax jtpvt ulbtd mfquuyhey qjzkrji rtc bxwag ugvyv olxvhjnb uxevss.
                + type: cumqlvqty
                + userId: 410000199005223658
                + createdAt: `2017-03-07T14:14:16.000Z`
                + user
                    + name: Donald Rodriguez

